stages:
  - test
  - build
  - push
  - deploy

variables:
  AWS_DEFAULT_REGION: ap-southeast-1
  ECR_REGISTRY: 164092712009.dkr.ecr.ap-southeast-1.amazonaws.com
  FRONTEND_IMAGE: $ECR_REGISTRY/kubex/frontend
  BACKEND_IMAGE: $ECR_REGISTRY/kubex/backend

# STAGE 1: TEST

test:frontend:
  stage: test
  image: node:20-alpine
  script:
    - cd frontend
    - npm install
    - npx tsc --noEmit
  only:
    - main

test:backend:
  stage: test
  image: node:20-alpine
  script:
    - cd backend
    - npm install
    - npx tsc --noEmit
  only:
    - main

# STAGE 2: BUILD

build:frontend:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $FRONTEND_IMAGE:$CI_COMMIT_SHORT_SHA -t $FRONTEND_IMAGE:latest ./frontend
  only:
    - main

build:backend:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA -t $BACKEND_IMAGE:latest ./backend
  only:
    - main

# STAGE 3: PUSH

push:images:
  stage: push
  tags:
    - docker
  script:
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
    - docker push $FRONTEND_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $FRONTEND_IMAGE:latest
    - docker push $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $BACKEND_IMAGE:latest
  only:
    - main

# STAGE 4: DEPLOY

deploy:k8s:
  stage: deploy
  tags:
    - docker
  script:
    - echo $KUBECONFIG_B64 | base64 -d > /tmp/kubeconfig
    - export KUBECONFIG=/tmp/kubeconfig
    - kubectl apply -f k8s/
    - kubectl rollout status deployment/frontend -n kubex --timeout=120s
    - kubectl rollout status deployment/backend -n kubex --timeout=120s
    - kubectl get pods -n kubex
  only:
    - main
