apiVersion: v1
kind: ConfigMap
metadata:
  name: kubex-config
  namespace: kubex
data:
  POSTGRES_DB: kubex_db
  POSTGRES_USER: kubex
  PORT: "3001"
  FRONTEND_URL: "https://gpu.kubex.my"
---
apiVersion: v1
kind: Secret
metadata:
  name: kubex-secret
  namespace: kubex
type: Opaque
stringData:
  POSTGRES_PASSWORD: kubex_password
  DATABASE_URL: postgresql://kubex:kubex_password@postgres-svc:5432/kubex_db
